"""Add roles in class

Revision ID: 07ea2e47979c
Revises: c425e1c115ce
Create Date: 2026-03-18 12:30:45.030952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07ea2e47979c'
down_revision: Union[str, Sequence[str], None] = 'c425e1c115ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usersAuth', sa.Column('roles', sa.ARRAY(sa.Enum('PUBLIC', 'EDITOR', 'ADMIN', name='role', native_enum=False)), nullable=False, server_default='{PUBLIC}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usersAuth', 'roles')
    # ### end Alembic commands ###
